### ISSUE TITLE
Caelan - Service discovery

### ISSUE THREAD

**Issue by me4502** [KnightHawk3/packr#10]
Caelan would like to find out the different services that On the Spot provide, so that he can make an informed decision on which services are appropriate for him.

**Comment by ZeroEcks** [comment]
Acceptance criteria:
- list of each delivery service
- details of the service (    )

**Comment by jordanchee** [comment]
Reviewed User Story:
As a client I want to find out the different services that On the Spot provide, so that I am able to make an informed decision on which service is the most appropriate to fulfil my needs.

**Comment by jordanchee** [comment]
Reviewed Acceptance Criteria:
As a client I am able to find out the different services that On the Spot provide by navigating to the 'Services' section of the On the Spot website. This section includes a list that highlights all the different delivery services available to me accompanied with various details of what each service entails. I am now able to make an informed decision on which service will be the most appropriate to fulfil my needs.
