### ISSUE TITLE
Dragan - Contact Information

### ISSUE THREAD

**Issue by me4502** [KnightHawk3/packr#11]
Dragan would like to access to On the Spots contact information in order to make further enquiries about On the Spots services.

**Comment by me4502** [comment]
Contact form - page with displayed messages.

**Comment by jordanchee** [comment]
Acceptance Criteria:
As a client I now have access to On the Spots contact information through accessing On the Spots website and navigating to the 'Contact Us' webpage which lists the following information: Phone Number, Fax, Email, Street Address (Inc. Map), Links to pre-existing On the Spot Social Media pages.

**Comment by ZeroEcks** [comment]
Still not done see #33

**Comment by jordanchee** [comment]
Reviewed User Story:
As a client I want to have access to On the Spots contact information in order to make further enquiries about On the Spots services.
