### ISSUE TITLE
Edwige - Ordering a Package

### ISSUE THREAD

**Issue by me4502** [KnightHawk3/packr#12]
Edwige is a customer who wants a package delivered. He places the order delivery through Packr, and it is delivered.

**Comment by ZeroEcks** [comment]
Acceptance criteria:
- specify package details (type - fragile etc, weight, size, number of packages)
- delivery details (pick up location, pick up time, delivery location)
-  comments
-  the delivery order is lodged
- notification that the order has been lodged

**Comment by ghost** [comment]
should we split this into separate stories? i.e. Client wants to enter how many packages they have; client wants to enter the weight and dimensions of packages; client wants to enter comments for special delivery details, etc...

**Comment by jordanchee** [comment]
Refined User Story:
As a client I want to place an order to have a package delivered to a specific location, at a specific time and would like to receive notifications on the status of my package.

**Comment by jordanchee** [comment]
Refined Acceptance Criteria:
As a client I am now able to access On the Spot's website and place an order to have a package delivered. Via the On the Spot website I am able to specify package details (type - fragile etc, weight, size, number of packages), delivery details (pick up location, pick up time, delivery location), notes and comments, notifications confirming that the order has been lodged.
