### ISSUE TITLE
Gerty - Preferred Payment Option

### ISSUE THREAD

**Issue by me4502** [KnightHawk3/packr#14]
Gerty is a delivery driver that would like to know the the customer's prefered payment option in order to become more efficient in order to streamline the delivery process.

**Comment by jordanchee** [comment]
Acceptance Criteria:
As a Delivery Driver I am able to find out the customers preferred payment option prior to completing the delivery of the package, as this information will be displayed on the Delivery Drivers scanner once he has scanned the packages Unique Identifier. Now the delivery process is more streamlined and has become more efficient.

**Comment by ZeroEcks** [comment]
Still not done see #7

**Comment by jordanchee** [comment]
Reviewed User Story:
As a driver I want to have access to the clients preferred payment option, prior to making the delivery, so that the delivery process becomes more efficient.
