### ISSUE TITLE
Herbie - Contacting the customer

### ISSUE THREAD

**Issue by me4502** [KnightHawk3/packr#16]
Herbie is a driver who would like to be able to contact the customer if anything happens whilst on his delivery.

**Comment by ghost** [comment]
Not sure this is really required, details would be on the con note, if the driver had any issues he would contact his manager not the customer. I guess we could add something for this if we were short on ideas

**Comment by Bridgetharbourne** [comment]
Acceptance Criteria:
- The delivery driver will be able to access customer’s contact details through the con note.
