### ISSUE TITLE
Ian - Setting the package status

### ISSUE THREAD

**Issue by me4502** [KnightHawk3/packr#17]
Ian is a customer who would like to set a specific status of his package to Fragile so the delivery driver knows to be careful with it.

**Comment by me4502** [comment]
Acceptance Criteria:
- Fragile status can be set and read

**Comment by Bridgetharbourne** [comment]
Ian is able to specify the status of his package to fragile through the ordering process on the website, which will then notify the driver of the status of the package.

**Comment by jordanchee** [comment]
Reviewed User Story:
As a customer I want to be able to set the status of my package to Fragile so the delivery drivers knows to handle the package with care.
