### ISSUE TITLE
Jenkins - Viewing the Payment Method

### ISSUE THREAD

**Issue by me4502** [KnightHawk3/packr#18]
Jenkins is a delivery driver who wants to be able to see what payment method  the customer needs to pay by card or by cash.

**Comment by ghost** [comment]
again this would be on the con note, not something we can integrate into the site

**Comment by ZeroEcks** [comment]
I would argue the site should have it because the site should be linked to the con note, ie is a part of the same system that generates the con note so the site should be able to store it.

**Comment by Bridgetharbourne** [comment]
Acceptance Criteria:
- As a delivery driver i can access the payment method selected by the customer through accessing the con note 
- I can also access the payment method through the website, as the con note is linked to the website
