### ISSUE TITLE
Client - view con note

### ISSUE THREAD

**Issue by ghost** [KnightHawk3/packr#23]
As a client I should be able to view the con note from the web site

**Comment by jordanchee** [comment]
As a client I am able to view the con note from the website, once the delivery has been complete and the packages unique identifier is scanned a copy of the con note is sent to one of On the Spots DATABASES, which is also linked to On the Spots website allow clients to view this information.

**Comment by ZeroEcks** [comment]
Depends on #34

**Comment by me4502** [comment]
Is this basically tracking a package? @Smurfenstein

**Comment by ghost** [comment]
no, this is what the receiver will sign to confirm receipt of the goods. It is then uploaded so the sender can see who signed for the package. It contains the addresses, package details, fragile or dangerous goods indicators. A lot of consignment notes are still hand written by the senders, but if the courier is using a digital device they can have the receiver sign that and auto generate a con note.

**Comment by me4502** [comment]
Okay, thanks
