### ISSUE TITLE
Client - specify pick up and delivery times

### ISSUE THREAD

**Issue by ghost** [KnightHawk3/packr#24]
As a client I should be able to specify what day and time the packages are to be picked up and delivered

**Comment by jordanchee** [comment]
As a client I am able to specify what day and time the packages are to be picked up and delivered by:

 a) including this information under Services section of the website, or
 b) directly contacting On the Spot via email or telephone and alerting them with this information.

**Comment by ZeroEcks** [comment]
Allow the admin to update the date and time of delivery (for phone calls) and the user.

**Comment by ZeroEcks** [comment]
Allow the driver to see when to deliver also.
