### ISSUE TITLE
Update the package model

### ISSUE THREAD

**Issue by ZeroEcks** [KnightHawk3/packr#3]
**Package model update progress**
- [x] Many to One with orders
- [x] Package UUID
- [x] Comments on delivery
- [x] Notes on delivery

**Comment by ZeroEcks** [comment]
Related to #8 #15

**Comment by me4502** [comment]
What exactly is the difference between comments on delivery and notes on delivery?

**Comment by ZeroEcks** [comment]
Notes on delivery are delivery notes like "avoid the dog" "leave it on my roof" and comments are between the admin and the driver with things like "this customer is a jerk leave his package until last"

**Comment by ZeroEcks** [comment]
Also delivery notes is a single text field where comments are like a comment stream

**Comment by me4502** [comment]
But wouldn't both of those make more sense in order? And there's already a field for order details.

**Comment by ZeroEcks** [comment]
Probably

**Comment by ZeroEcks** [comment]
What if a comment is about a specific package

**Comment by ZeroEcks** [comment]
"this one barks if you drop it" sorta thing

**Comment by me4502** [comment]
well then wouldn't a boolean fragile field make more sense per package, and then have the notes on the main order? Also - shouldn't weight also be on the packages as well?

**Comment by ZeroEcks** [comment]
What if it's an explosive or acid or smth, maybe have a options field with
all the dangerous goods types

Yes weight should be on the packages I say

**Comment by me4502** [comment]
Okay, so we have both a boolean fragile and dangerous field

Because it could be either, none, or both

**Comment by ZeroEcks** [comment]
Theres 9 classes of dangerous goods:

http://www.dgiglobal.com/classes

You should make a dangerous field with those choices as the only acceptable input and a fragile boolean

**Comment by ghost** [comment]
small couriers wont carry any dangerous goods, unless they are a specialized company

**Comment by ZeroEcks** [comment]
Obviously we are making it portable so we can sell it to other companies :wink:
