### ISSUE TITLE
Addison - Specific comments for delivery

### ISSUE THREAD

**Issue by me4502** [KnightHawk3/packr#8]
Addison is a customer that would like to be able to go onto the website and add specific comments to the delivery that the driver will be able to see and take note.

Related to #15

**Comment by DayeHorse3** [comment]
Acceptance Criteria
- If the customer is able to access the website and easily able to navigate to the comment section.
- The Driver is able to see and take note of any comments sent by customer.

**Comment by jordanchee** [comment]
Reviewed User Story:
As a customer I want to be able to leave specific comments and notes for the delivery driver, relating to the delivery of the package.

**Comment by jordanchee** [comment]
Reviewed Acceptance Criteria:
As a customer I am able to leave specific comments and notes for the delivery driver through accessing the On the Spot website. This can be done either during the initial ordering process or subsequent to this by using the packages unique identifier and amending the order details.
