### ISSUE TITLE
Britney - Package Tracking

### ISSUE THREAD

**Issue by me4502** [KnightHawk3/packr#9]
Britney is a customer that would like to use the packages unique identifier to find out the status of her packages location. (Status includes: Location of package, ETA)

**Comment by ZeroEcks** [comment]
Acceptance criteria:
- The customer is able to log into her account and input her Unique ID to find the status of her packages location. 
- The customer should be able to see the status list of package as Booked, picked up, in storage, in transit, shipped, delivered. Date and time stamp needs to be included.

**Comment by ghost** [comment]
Status indicators should be: Booked, picked up, in storage, in transit, delivered. Date and time stamp needs to be included
